# Generated by Django 5.1 on 2024-10-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regester',
            name='password',
            field=models.CharField(default='sarthak', max_length=8),
        ),
    ]
