# Generated by Django 5.1 on 2024-10-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_regester_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_addresh', models.CharField(max_length=100)),
                ('student_roll_number', models.IntegerField()),
                ('student_section', models.CharField(max_length=1)),
                ('student_marks_math', models.IntegerField()),
                ('student_marks_Digital_logic', models.IntegerField()),
                ('student_marks_programing', models.IntegerField()),
                ('student_marks_discrete', models.IntegerField()),
            ],
        ),
    ]
