# Generated by Django 5.1 on 2024-11-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_student_addresh_student_student_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_marks_Digital_logic',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
